### ISSUE TITLE
Guidance with installing on Mac OS X

### ISSUE THREAD

**Issue by juviwhale** [izderadicka/pdfparser#10]
Maybe the the right place for this, but do you have any guidance with installing on Mac OS X?
Maybe this be added to the readme.

**Comment by izderadicka** [comment]
There has been some issues with comments on Mac - as I understood  C++11 switch is needed for compilation. As I do now work on Mac I do not provide official guidance, but if you want to provide PR, It's welcomed.

**Comment by max-ionov** [comment]
I have fixed issues on Mac OS, it works on my system. Pull request is here: #13
Please test if it works for you.

**Comment by izderadicka** [comment]
I hope PR from Max resolved this issue. I merged it to master.
