### ISSUE TITLE
Error installing master through pip

### ISSUE THREAD

**Issue by oplahcinski** [izderadicka/pdfparser#12]
I get the follow back from fabric while installing on my machines.

I went back to my fork to solve the problem, it looks like poppler-cpp was added into the pkgconfig the other day where as it wasnt in the previous build

        Complete output from command python setup.py egg_info:
        Package poppler-cpp was not found in the pkg-config search path.
        Perhaps you should add the directory containing `poppler-cpp.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'poppler-cpp' found
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-cstq2sf7-build/setup.py", line 76, in <module>
            poppler_config = pkgconfig("poppler", "poppler-cpp")
          File "/tmp/pip-cstq2sf7-build/setup.py", line 61, in pkgconfig
            items = subprocess.check_output(['pkg-config', optional_args, pkg_option, package]).decode('utf8').split()
          File "/usr/lib64/python3.6/subprocess.py", line 336, in check_output
            **kwargs).stdout
          File "/usr/lib64/python3.6/subprocess.py", line 418, in run
            output=stdout, stderr=stderr)
        subprocess.CalledProcessError: Command '['pkg-config', '', '--cflags-only-I', 'poppler-cpp']' returned non-zero exit status 1.
     out:
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-cstq2sf7-build/

**Comment by izderadicka** [comment]
Yes, now it's dependent also on poppler-cpp so you should  install it too - I tried to update readme.  
poppler-cpp is now used to provide version of poppler library ( maybe in future  it can be leveraged for more).

**Comment by izderadicka** [comment]
Closing - I hope new readme clearly states dependency on libpoppler-cpp too.
