### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by friedelwolff** [izderadicka/pdfparser#2]
Thanks for the work on pdfparser! Is it possible to clarify the license please? You mention it is GPLv3. Is that with or without the "or any later version" clause? Would you accept a pull request to clarify this?

**Comment by izderadicka** [comment]
Any later versions would be fine with me.  My intention was mainly to assure that license is compatible libpoppler license.   PR is welcomed. And thanks for other PR - I'll look at it later

**Comment by izderadicka** [comment]
updated in readme in commit ee754b1
